# AUTOGENERATED! DO NOT EDIT! File to edit: 06_DataStruct_Fixture.ipynb (unless otherwise specified).

__all__ = ['Fixture']

# Cell
from mongoengine import DynamicDocument, IntField
from ..config.localconfig import CONFIG

# Cell
class Fixture(DynamicDocument):
    """
        A class to represent the opta fixtures.

    ...

    Attributes
    ----------
    gameId : int
        the opta game id
    CompetitionId : int
        the competition id of the match

    """
    gameId = IntField(db_field="gameId")
    competitionId = IntField(db_field="competitionId")
    meta = {
        "db_alias": "opta",
        "collection": CONFIG["connections"]["opta"]["fixture"],
    }