# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CONFIG": "000_config.ipynb",
         "DB_HOSTS": "000_config.ipynb",
         "db_connect": "001_mongo.ipynb",
         "mongo_init": "001_mongo.ipynb",
         "ScrapingTheGuardian": "00_scraper.ipynb",
         "Parser": "01_parser.ipynb",
         "PageExtractor": "02_extractor.ipynb",
         "PreviewsMapping": "04_mapper.ipynb",
         "Previews": "05_DataStruct_Previews.ipynb",
         "Fixture": "06_DataStruct_Fixture.ipynb"}

modules = ["config/localconfig.py",
           "config/mongo.py",
           "scraper.py",
           "parser.py",
           "extractor.py",
           "mapper.py",
           "models/preview.py",
           "models/fixture.py"]

doc_url = "https://MeherKharbachi.github.io/theguardianscraper/"

git_url = "https://github.com/MeherKharbachi/theguardianscraper/tree/master/"

def custom_doc_links(name): return None
