# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Parser": "00_scraper.ipynb",
         "PageExtractor": "00_scraper.ipynb",
         "ScrapingTheGuardian": "00_scraper.ipynb"}

modules = ["scraper.py"]

doc_url = "https://MeherKharbachi.github.io/TheGuardianScraper/"

git_url = "https://github.com/MeherKharbachi/TheGuardianScraper/tree/master/"

def custom_doc_links(name): return None
