# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Parser": "00_scraper.ipynb",
         "PageExtractor": "00_scraper.ipynb",
         "ScrapingTheGuardian": "00_scraper.ipynb",
         "PreviewsMapping": "00_scraper.ipynb",
         "Previews": "00_scraper.ipynb",
         "MongoClient": "00_scraper.ipynb"}

modules = ["scraper.py"]

doc_url = "https://MeherKharbachi.github.io/guardian_scraper/"

git_url = "https://github.com/MeherKharbachi/guardian_scraper/tree/master/"

def custom_doc_links(name): return None
